name: build
on:
  push:

jobs:
  build-macos:
    runs-on: macos-13
    strategy:
      matrix:
        arch: [win64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          # arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          # eval "$(/usr/local/bin/brew shellenv)"
          # arch -x86_64 brew install --overwrite python
          find /usr/local -iname libfreetype.6.dylib
          clang -o test test.c
          echo $DYLD_LIBRARY_PATH
          ./test
          export DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH
          ./test

          # arch -x86_64 $PWD/build-macos ${{ matrix.arch }}
